### PR TITLE
Adding curly rule

### PR DESCRIPTION
**Pull request by eduardojmatos**
Our proposal is always to use curly braces. Sample:

```JavaScript
// Bad
if ('condition') return true;

// Good
if ('condition') {
  return true;
}


// Bad
if ('condition') condition();
else notCondition();

// Good
if ('condition') {
  condition();
} else {
  notCondition();
}

```

### CODE REVIEW

**Review by felipeorlando — APPROVED** [review]
Sad 😢

**Review by iondrimba — APPROVED** [review]

**Comment by CaioCSdev** [comment]
Que tal?

```javascript
// Better
if ('condition') {
  condition();
}
else {
  notCondition();
}

**Comment by eduardojmatos** [comment]
@Eliada bem estranho heheh

Pra mim ⛔️

**Review by wbotelhos — APPROVED** [review]
conflict

**Review by williamcosta — APPROVED** [review]
:shipit:

**Review by nathpaiva — APPROVED** [review]

**Pull request merged**
